root = "."
tmp_dir = "build"

[build]
  cmd = "go build -o ./build/ ./src/main.go"
  bin = "build/main"
  full_bin = "./build/main"
  args_bin = []
  include_ext = ["go", "html"]
  exclude_dir = [".vscode", "build"]
  include_dir = []
  include_file = []
  exclude_file = ["data.sqlite"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  log = "build-errors.log"
  poll = false
  poll_interval = 500
  delay = 1000
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500
  rerun = false
  rerun_delay = 500

[log]
  time = false
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true